### ISSUE TITLE
Licence is unclear

### ISSUE THREAD

**Issue by symphorien** [Josef-Friedrich/check_systemd#11]
Setup.py says LGPL v2

https://github.com/Josef-Friedrich/check_systemd/blob/v2.2.1/setup.py#L42

Source says GPL v2

https://github.com/Josef-Friedrich/check_systemd/blob/v2.2.1/check_systemd.py#L4-L6

The phrasing is unclear: v2 only or any later version ?

**Comment by Josef-Friedrich** [comment]
The license should now be clear.
