### ISSUE TITLE
Debian packaging meta-issue

### ISSUE THREAD

**Issue by baldurmen** [Josef-Friedrich/check_systemd#13]
Hi!

Thanks for maintaining this check! I find it very useful so [I decided to package it in Debian](https://ftp-master.debian.org/new/monitoring-plugins-systemd_2.3.0+ds-1.html).

It is currently going through the pre-approval step (NEW) and sadly won't make it in the upcoming stable version (Debian 11 "Bullseye") because I've missed the deadline, but chances are I'll be backporting it.

I have a few questions for you, so I decided a meta-issue was a better idea than opening 3 different issues :)

1. Do you mind if I package this in Debian? If you do, I'll be glad to remove it from the archive.

2. I'm not sure I understand why there are embedded copies of systemd C code in `systemd_source_code`. AFAICT, this is not needed to run the test suite properly. You added that code in 6897770e1335fe460b4adb2b8ff9d7d4b77fd03d, but the commit message isn't clear enough for me to understand the reason behind it.

3. Would you be open to signing future git tags with a GPG key? It would reinforce the chain of trust when I package new versions. I'd need a copy of your public key though.

If you want to have a look at it, [here's my packaging work](https://salsa.debian.org/python-team/packages/monitoring-plugins-systemd/-/tree/debian/master/debian).

Cheers,

**Comment by Josef-Friedrich** [comment]
* add 1.: That is a great honor for this project when there will be a Debian package.
* add 2.: I have [removed the confusing source code files](https://github.com/Josef-Friedrich/check_systemd/commit/07ae5caedcf4a7a13442eed8c2c9582275cdc16a) and replaced them with links.
* add 3.: I have never signed a tag with GPG before, but I will learn. After all, I have already sent 2 GPG encrypted emails. Here is my public key: https://josef.friedrich.rocks/meta/gpg.html

Many thanks for your commitment to get a Debian package on the way

**Comment by baldurmen** [comment]
Good to hear!

I find this is not a bad tutorial on how to sign git tags: https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
