### ISSUE TITLE
New release to include `--user` option

### ISSUE THREAD

**Issue by duncanmmacleod** [Josef-Friedrich/check_systemd#29]
Dear @Josef-Friedrich, I am just discovering this tool, it looks like a very good fit for my organisation's needs, thanks for maintaining it! Is it possible to request a new release on PyPI that includes the new `--user` option provided by #22?

**Comment by Josef-Friedrich** [comment]
You are right, a new version should be published on PyPI. But I ask for a little patience. I have to write some release notes.

**Comment by duncanmmacleod** [comment]
> I ask for a little patience. I have to write some release notes.

@Josef-Friedrich, thank you! This is not urgent for my project, and if it was, I should be offering to help. Whenever you can get to this is great.

**Comment by Josef-Friedrich** [comment]
voilà: https://pypi.org/project/check_systemd/3.0.0/
