### ISSUE TITLE
Icinga complains about invalid perfdata

### ISSUE THREAD

**Issue by rolatsch** [Josef-Friedrich/check_systemd#32]
The attribute `data_source` which is reported as part of the perfdata from this plugin can not be evaluated by icinga. 

Is there any way to fix or workaround this issue or to exclude this attribute from the data.

![grafik](https://github.com/Josef-Friedrich/check_systemd/assets/17025707/29e0d215-81f4-42b3-a7a5-06eb570ba288)

Thanks in advance!

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this.

I removed the attribute `data_source`.

I wrote the wrong issue number in the commit message

https://github.com/Josef-Friedrich/check_systemd/commit/62fd828177c9372a5234314e354ca9a442e726bb

Could you please test the current main branch

**Comment by rolatsch** [comment]
Thank you for the quick response.

`data_source` is gone now 👍 
![grafik](https://github.com/Josef-Friedrich/check_systemd/assets/17025707/9410f80a-9c89-40d7-ba2f-01cf9659a744)

how long does it take for the new version to arrive in the monitoring-plugins package?

**Comment by Josef-Friedrich** [comment]
I will release a new Version on PyPI. But I’m not sure which version  3.1.1, 3.2.0 or even 4.0.0? A major version change seems a little excessive to me. Probably 3.1.1 ... To be honest, I don't know when the update will end up in the monitoring package. 

You can use the plugin as a standalone script in the meantime, as it only depends on nagiosplugin.

**Comment by rolatsch** [comment]
Thanks for the information.
Depending on the point of view, this change is a breaking change and would therefore require a major release according to semver.

**Comment by Josef-Friedrich** [comment]
https://pypi.org/project/check_systemd/4.0.0/
