### ISSUE TITLE
Ignoring invalid perfdata for checkable with value: data_source=cli

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [Josef-Friedrich/check_systemd#33]
It doesn't seem to like the text string metric `data_source`. Should it just be removed?

**Comment by Josef-Friedrich** [comment]
See https://github.com/Josef-Friedrich/check_systemd/issues/32

In version 4.0.0 this was fixed

**Comment by Engineer-of-Stuff** [comment]
Oh, must be on an older version. Thx
