### ISSUE TITLE
ValueError or SYSTEMD OK when service is stopped

### ISSUE THREAD

**Issue by JonahArends** [Josef-Friedrich/check_systemd#34]
OS: Ubuntu 22.04.4 LTS
Version: check_systemd 4.0.0 *(installed via pip on 26.02.2024)*

- **Command:** `check_systemd --unit fail2ban`
- **Output:** `SYSTEMD UNKNOWN: ValueError: Please verify your --include-* and --exclude-* options. No units have been added for testing.`
- **Verbose output:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nagiosplugin/runtime.py", line 45, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/check_systemd.py", line 1465, in main
    check.main(opts.verbose)
  File "/usr/local/lib/python3.10/dist-packages/nagiosplugin/check.py", line 122, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/local/lib/python3.10/dist-packages/nagiosplugin/runtime.py", line 132, in execute
    self.run(check)
  File "/usr/local/lib/python3.10/dist-packages/nagiosplugin/runtime.py", line 119, in run
    check()
  File "/usr/local/lib/python3.10/dist-packages/nagiosplugin/check.py", line 107, in __call__
    self._evaluate_resource(resource)
  File "/usr/local/lib/python3.10/dist-packages/nagiosplugin/check.py", line 81, in _evaluate_resource
    for metric in metrics:
  File "/usr/local/lib/python3.10/dist-packages/check_systemd.py", line 836, in probe
    raise ValueError(
ValueError: Please verify your --include-* and --exclude-* options. No units have been added for testing.
```
- **Expected Output:** `SYSTEMD CRITICAL - fail2ban.service: inactive`...
---
- **Command:** `check_systemd --unit clamav-daemon`
- **Output:** `SYSTEMD OK - clamav-daemon.service: inactive | count_units=440 startup_time=9.56;60;120 units_activating=0 units_active=310 units_failed=0 units_inactive=130`
- **Expected Output:** `SYSTEMD CRITICAL - fail2ban.service: inactive`...
---
When the services are started, everything runs as expected. But when they are stopped, different, incorrect outputs appear.
The problem occurs with two new servers that are monitored with Icinga2.
I have cross-checked the output from Icinga with the CLI on both servers.

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this issue:

A few lines of the program call 

```
systemctl list-units --all
```

would be very helpful

**Comment by JonahArends** [comment]
If fail2ban is stopped, there is no output for `sudo systemctl list-units --all | grep fail2ban`.

For `sudo systemctl list-units --all | grep clamav` with deactivated daemon:
```
  clamav-daemon.service loaded inactive dead Clam AntiVirus userspace daemon
  clamav-freshclam.service loaded active running ClamAV virus database updater
```

When both are started, the following appears:
```
sudo systemctl list-units --all | grep fail2ban
  fail2ban.service loaded active running Fail2Ban Service
```
```
sudo systemctl list-units --all | grep clamav
  clamav-daemon.service loaded inactive dead Clam AntiVirus userspace daemon
  clamav-freshclam.service loaded active running ClamAV virus database updater
```

**Comment by Josef-Friedrich** [comment]
Thank you for the additional informations. 
May I ask for further information. What is the output of the following command when the service is stopped and the service is running. Thank you in advance

```
systemctl show failban | grep -E 'Id|Names|Type|ActiveState|SubState|LoadState'
```

**Comment by JonahArends** [comment]
fail2ban running:
```
RestrictNamespaces=no
Id=failban.service
Names=failban.service
LoadState=not-found
ActiveState=inactive
SubState=dead
```

fail2ban stopped:
```
RestrictNamespaces=no
Id=failban.service
Names=failban.service
LoadState=not-found
ActiveState=inactive
SubState=dead
```

**Comment by Josef-Friedrich** [comment]
Are you sure? There should be a difference between the running state and the stopped state

**Comment by JonahArends** [comment]
Here is a screenshot of the commands I am executing:
![check_systemd](https://github.com/Josef-Friedrich/check_systemd/assets/122887053/80a2775d-79aa-4241-8245-a7d1ec332655)

**Comment by JonahArends** [comment]
Here is a screenshot of the commands I am executing:
![check_systemd](https://github.com/Josef-Friedrich/check_systemd/assets/122887053/1b83ea19-1376-4340-bc3f-127be4feb77f)

**Comment by Josef-Friedrich** [comment]
As I see it now, it is not enough to parse the command `systemctl list-units --all`. In addition, the command `systemctl show <unit>` must be called by check_systemd.py, if the option `--unit` is specified. Some things probably need to be adjusted. Please be patient, pull requests are of course very welcome.

**Comment by Josef-Friedrich** [comment]
Could you please test the current version of the main branch

A stopped fail2ban service should new result in a cricital state if you specify an additional argument:

```
./check_systemd.py --unit fail2ban.service --state active
```

**Comment by JonahArends** [comment]
It works:
```
SYSTEMD CRITICAL - fail2ban.service: inactive | count_units=463 startup_time=9.56;60;120 units_activating=0 units_active=337 units_failed=0 units_inactive=126
```

**Comment by Josef-Friedrich** [comment]
https://pypi.org/project/check_systemd/4.1.0/
