### ISSUE TITLE
static binary and rpm file

### ISSUE THREAD

**Issue by schubba** [Josef-Friedrich/check_systemd#39]
Hi there,

I wanted to share something a bit unconventional I did with check_systemd. I managed to create a static binary using Nuitka and wrapped it up in an RPM package. You can find the project here: https://gitlab.com/msfgitlab/check_systemd_build_rpm.

I know it might sound a bit over the top (or maybe even a bit silly), but it works! 😅 However, I'm not entirely sure when or if it will break, especially considering potential issues with incompatible Python versions or other dependencies in the future.

I'd really appreciate any thoughts or suggestions for improvement you might have. If this approach piques your interest or you have any tips to make it more robust, I'm all ears!

Thanks for your work on check_systemd!

Best regards,

martin

**Comment by Josef-Friedrich** [comment]
Thank you for packaging check_systemd for Oracle Linux: Unfortunately, I have no experience with Nuitka. I have to admit that I have never heard of Nuitka. If your packaging breaks through Nuitka ... I'm sure you are there and can fix the problem very quickly

Could you please add your package to this list via pull request:

https://github.com/Josef-Friedrich/check_systemd/blob/main/README_template.rst#packages

Please edit the file README_template.rst

**Comment by schubba** [comment]
https://github.com/Josef-Friedrich/check_systemd/pull/40
