### ISSUE TITLE
Option to don't check startup time

### ISSUE THREAD

**Issue by kepi** [Josef-Friedrich/check_systemd#7]
IMHO it might be sometime needed to disable check for startup time. Not only because we don't care, but there might be situations where `systemd-analyze` is not really dependable.

Here is one real-world example :laughing: 

```console
$ systemd-analyze
Startup finished in 4.257s (kernel) + 16h 57min 45.442s (userspace) = 16h 57min 49.699s
```

Feel free to decline this as I don't really need it. In fact in this case it would be usefull if check would alert me sooner and I can fix/stop the service which was starting so long :)

**Comment by Josef-Friedrich** [comment]
Should be fixed.

**Comment by kepi** [comment]
Works like a charm, thanks!
