### ISSUE TITLE
Problem while SELinux is in Enforcing mode

### ISSUE THREAD

**Issue by karloff10** [Josef-Friedrich/check_systemd#9]
I have a problem with calling check_systemd with icinga2 when SELinux is active on the client.
Once SELinux is disabled everything works as intended, is there a way to use check_systemd on a system running SELinux in enforcing mode?
Creating a SELinux modular policy (.pp file) does not solve the problem.

**Comment by Josef-Friedrich** [comment]
Unfortunately, I have no experience with SELinux.
